name: news
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.3+1 #2.0.3+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3
  provider: ^6.0.4
  shared_preferences: ^2.0.7
  jaguar_jwt: ^3.0.0
  connectivity: ^3.0.6
  country_code_picker: ^2.0.2
  sms_autofill: ^2.0.1
  http: ^0.13.3
  location: ^4.3.0
  intl: ^0.17.0
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.1
  google_sign_in: ^5.1.0
  photo_view: ^0.14.0
  url_launcher: ^6.0.10
  shimmer: ^2.0.0
  firebase_dynamic_links: ^5.0.1
  share: ^2.0.4
  flutter_tts: ^3.2.2
  image_picker: ^0.8.4+1
  video_player: ^2.2.5
  flick_video_player: ^0.5.0
  youtube_player_flutter: ^8.0.0
  in_app_review: ^2.0.3
  flutter_local_notifications: ^9.9.1
  firebase_messaging: ^14.0.1
  path_provider: ^2.0.5
  #flutter_login_facebook: ^1.1.0 #//fbAud
  #flutter_login_facebook: ^1.5.0+1
  flutter_login_facebook: ^1.6.0
  #apple_sign_in_safety: ^0.0.6
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.1
  facebook_audience_network: ^1.0.1 #//fbAud
  percent_indicator: ^4.0.0
  google_mobile_ads: ^2.1.0
  device_info_plus: ^3.2.4
  cached_network_image: ^3.2.0
  flutter_widget_from_html_core: ^0.8.5+3
  # fwfh_webview: ^0.6.2+2
  flutter_widget_from_html: ^0.8.5
  unity_ads_plugin: ^0.3.7
  permission_handler: ^10.0.0
  flutter_inappwebview: ^5.7.1
  #flutter_inappwebview: ^5.5.0+2
  video_thumbnail: ^0.5.3
  html_editor_enhanced: ^2.5.0
  path_drawing: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/flag/
    - lib/Language/en.json
    - lib/Language/es.json
    - lib/Language/hi.json
    - lib/Language/tr.json
    - lib/Language/pt.json
    - lib/Language/ar.json
    - lib/Language/he.json
  fonts:
  #  - family: Neue Helvetica
  #   fonts:
  #      - asset: assets/font/Helvetica Neue LT 55 Roman.ttf
  #      - asset: assets/font/Helvetica Neue LT 65 Medium.ttf
  #        weight: 600
  #      - asset: assets/font/Helvetica Neue LT 75 Bold.ttf
  #        weight: 800

    - family: Sarabun
      fonts:
        - asset: assets/font/Sarabun-Regular.ttf
        - asset: assets/font/Sarabun-Semibold.ttf
        - asset: assets/font/Sarabun-light.ttf
        - asset: assets/font/Sarabun-Medium.ttf
          weight: 600
        - asset: assets/font/Sarabun-Bold.ttf
          weight: 800




  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
